services:
  telegram-forwarder:
    image: ghcr.io/paulohgodinho/telegram-forwarder:latest
    environment:
      WEB_AUTH_PORT: ${WEB_AUTH_PORT:-56899}
      TELEGRAM_APP_ID: ${TELEGRAM_APP_ID}
      TELEGRAM_APP_HASH: ${TELEGRAM_APP_HASH}
      TELEGRAM_TG_PHONE: ${TELEGRAM_TG_PHONE}
      TELEGRAM_N8N_WEBHOOK_URL: ${TELEGRAM_N8N_WEBHOOK_URL}
    ports:
      - "${WEB_AUTH_PORT:-56899}:${WEB_AUTH_PORT:-56899}"
    volumes:
      - telegram-forwarder-session:/app/session
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.telegram-forwarder.rule=Host(`telegram-forwarder.internal.ghomelab.top`)"
      - "traefik.http.services.telegram-forwarder.loadbalancer.server.port=${WEB_AUTH_PORT:-56899}"
      - "traefik.docker.network=traefik-network"
    container_name: telegram-forwarder
    restart: unless-stopped

volumes:
  telegram-forwarder-session:
